<?php
/**
 * File: modules/reports/index.php
 * Reports dashboard
 * @version 1.0.1
 * @integration_verification PMSFV-025
 */
$page_title = "Reports";
require_once '../../includes/header.php';
require_once '../../includes/functions.php';

// Check if user has appropriate permissions
if (!in_array($_SESSION['user_role'], ['admin', 'manager'])) {
    $_SESSION['error_msg'] = "You don't have permission to access this page.";
    header("Location: " . BASE_URL . "dashboard.php");
    exit();
}

// Get recent generated reports
$stmt = $pdo->query("
    SELECT gr.*, rt.template_name, u.username as generated_by_name
    FROM generated_reports gr
    JOIN report_templates rt ON gr.template_id = rt.id
    JOIN users u ON gr.generated_by = u.id
    ORDER BY gr.generated_at DESC
    LIMIT 5
");
$recent_reports = $stmt->fetchAll();

// Get report templates
$stmt = $pdo->query("
    SELECT rt.*, u.username as created_by_name
    FROM report_templates rt
    JOIN users u ON rt.created_by = u.id
    ORDER BY rt.template_name
");
$report_templates = $stmt->fetchAll();

// Group templates by type
$grouped_templates = [];
foreach ($report_templates as $template) {
    $grouped_templates[$template['report_type']][] = $template;
}
?>

<div class="mb-4 flex justify-between items-center">
    <h1 class="text-2xl font-bold">Reports</h1>
    <div class="flex space-x-2">
        <a href="custom_report.php" class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded">
            <i class="fas fa-plus mr-2"></i>Custom Report
        </a>
        <a href="scheduled_reports.php" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
            <i class="fas fa-clock mr-2"></i>Scheduled Reports
        </a>
        <a href="templates.php" class="bg-purple-500 hover:bg-purple-700 text-white font-bold py-2 px-4 rounded">
            <i class="fas fa-file-alt mr-2"></i>Manage Templates
        </a>
    </div>
</div>

<?php
if (isset($_SESSION['success_msg'])) {
    echo "<div class='bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded relative mb-4' role='alert'>{$_SESSION['success_msg']}</div>";
    unset($_SESSION['success_msg']);
}
if (isset($_SESSION['error_msg'])) {
    echo "<div class='bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative mb-4' role='alert'>{$_SESSION['error_msg']}</div>";
    unset($_SESSION['error_msg']);
}
?>

<!-- Recent Reports -->
<div class="bg-white rounded-lg shadow p-6 mb-6">
    <div class="flex justify-between items-center mb-4">
        <h2 class="text-lg font-semibold">Recently Generated Reports</h2>
        <a href="history.php" class="text-blue-500 hover:text-blue-700">View All</a>
    </div>
    
    <?php if (count($recent_reports) > 0): ?>
        <div class="overflow-x-auto">
            <table class="min-w-full bg-white">
                <thead>
                    <tr class="bg-gray-200 text-gray-600 uppercase text-sm leading-normal">
                        <th class="py-3 px-6 text-left">Report Name</th>
                        <th class="py-3 px-6 text-left">Type</th>
                        <th class="py-3 px-6 text-center">Generated By</th>
                        <th class="py-3 px-6 text-center">Date</th>
                        <th class="py-3 px-6 text-center">Actions</th>
                    </tr>
                </thead>
                <tbody class="text-gray-600 text-sm">
                    <?php foreach ($recent_reports as $report): ?>
                        <tr class="border-b border-gray-200 hover:bg-gray-100">
                            <td class="py-3 px-6 text-left">
                                <?php echo htmlspecialchars($report['report_name']); ?>
                            </td>
                            <td class="py-3 px-6 text-left">
                                <?php echo ucfirst(str_replace('_', ' ', $report['template_name'])); ?>
                            </td>
                            <td class="py-3 px-6 text-center">
                                <?php echo htmlspecialchars($report['generated_by_name']); ?>
                            </td>
                            <td class="py-3 px-6 text-center">
                                <?php echo formatDateTime($report['generated_at']); ?>
                            </td>
                            <td class="py-3 px-6 text-center">
                                <div class="flex item-center justify-center">
                                    <a href="view_report.php?id=<?php echo $report['id']; ?>" class="w-4 mr-2 transform hover:text-purple-500 hover:scale-110">
                                        <i class="fas fa-eye"></i>
                                    </a>
                                    <a href="<?php echo $report['file_path']; ?>" download class="w-4 mr-2 transform hover:text-green-500 hover:scale-110">
                                        <i class="fas fa-download"></i>
                                    </a>
                                </div>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    <?php else: ?>
        <p class="text-gray-600">No reports have been generated yet.</p>
    <?php endif; ?>
</div>

<!-- Report Categories -->
<div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
    <!-- Production Reports -->
    <div class="bg-white rounded-lg shadow p-6">
        <h2 class="text-lg font-semibold mb-4">Production Reports</h2>
        <ul class="space-y-2">
            <?php if (isset($grouped_templates['production'])): ?>
                <?php foreach ($grouped_templates['production'] as $template): ?>
                    <li>
                        <a href="generate.php?template_id=<?php echo $template['id']; ?>" class="flex items-center p-2 hover:bg-blue-50 rounded">
                            <i class="fas fa-chart-line text-blue-500 mr-2"></i>
                            <span><?php echo htmlspecialchars($template['template_name']); ?></span>
                        </a>
                    </li>
                <?php endforeach; ?>
            <?php else: ?>
                <li class="text-gray-500">No production report templates available</li>
            <?php endif; ?>
            <li class="mt-4">
                <a href="custom_report.php?type=production" class="text-sm text-blue-500 hover:text-blue-700">
                    <i class="fas fa-plus mr-1"></i> Create Custom Production Report
                </a>
            </li>
        </ul>
    </div>
    
    <!-- Financial Reports -->
    <div class="bg-white rounded-lg shadow p-6">
        <h2 class="text-lg font-semibold mb-4">Financial Reports</h2>
        <ul class="space-y-2">
            <?php if (isset($grouped_templates['financial'])): ?>
                <?php foreach ($grouped_templates['financial'] as $template): ?>
                    <li>
                        <a href="generate.php?template_id=<?php echo $template['id']; ?>" class="flex items-center p-2 hover:bg-blue-50 rounded">
                            <i class="fas fa-money-bill-wave text-green-500 mr-2"></i>
                            <span><?php echo htmlspecialchars($template['template_name']); ?></span>
                        </a>
                    </li>
                <?php endforeach; ?>
            <?php else: ?>
                <li class="text-gray-500">No financial report templates available</li>
            <?php endif; ?>
            <li class="mt-4">
                <a href="custom_report.php?type=financial" class="text-sm text-blue-500 hover:text-blue-700">
                    <i class="fas fa-plus mr-1"></i> Create Custom Financial Report
                </a>
            </li>
        </ul>
    </div>
    
    <!-- Inventory Reports -->
    <div class="bg-white rounded-lg shadow p-6">
        <h2 class="text-lg font-semibold mb-4">Inventory Reports</h2>
        <ul class="space-y-2">
            <?php if (isset($grouped_templates['inventory'])): ?>
                <?php foreach ($grouped_templates['inventory'] as $template): ?>
                    <li>
                        <a href="generate.php?template_id=<?php echo $template['id']; ?>" class="flex items-center p-2 hover:bg-blue-50 rounded">
                            <i class="fas fa-boxes text-yellow-500 mr-2"></i>
                            <span><?php echo htmlspecialchars($template['template_name']); ?></span>
                        </a>
                    </li>
                <?php endforeach; ?>
            <?php else: ?>
                <li class="text-gray-500">No inventory report templates available</li>
            <?php endif; ?>
            <li class="mt-4">
                <a href="custom_report.php?type=inventory" class="text-sm text-blue-500 hover:text-blue-700">
                    <i class="fas fa-plus mr-1"></i> Create Custom Inventory Report
                </a>
            </li>
        </ul>
    </div>
    
    <!-- Employee Reports -->
    <div class="bg-white rounded-lg shadow p-6">
        <h2 class="text-lg font-semibold mb-4">Employee Reports</h2>
        <ul class="space-y-2">
            <?php if (isset($grouped_templates['employee'])): ?>
                <?php foreach ($grouped_templates['employee'] as $template): ?>
                    <li>
                        <a href="generate.php?template_id=<?php echo $template['id']; ?>" class="flex items-center p-2 hover:bg-blue-50 rounded">
                            <i class="fas fa-users text-purple-500 mr-2"></i>
                            <span><?php echo htmlspecialchars($template['template_name']); ?></span>
                        </a>
                    </li>
                <?php endforeach; ?>
            <?php else: ?>
                <li class="text-gray-500">No employee report templates available</li>
            <?php endif; ?>
            <li class="mt-4">
                <a href="custom_report.php?type=employee" class="text-sm text-blue-500 hover:text-blue-700">
                    <i class="fas fa-plus mr-1"></i> Create Custom Employee Report
                </a>
            </li>
        </ul>
    </div>
    
    <!-- Health Reports -->
    <div class="bg-white rounded-lg shadow p-6">
        <h2 class="text-lg font-semibold mb-4">Health Reports</h2>
        <ul class="space-y-2">
            <?php if (isset($grouped_templates['health'])): ?>
                <?php foreach ($grouped_templates['health'] as $template): ?>
                    <li>
                        <a href="generate.php?template_id=<?php echo $template['id']; ?>" class="flex items-center p-2 hover:bg-blue-50 rounded">
                            <i class="fas fa-heartbeat text-red-500 mr-2"></i>
                            <span><?php echo htmlspecialchars($template['template_name']); ?></span>
                        </a>
                    </li>
                <?php endforeach; ?>
            <?php else: ?>
                <li class="text-gray-500">No health report templates available</li>
            <?php endif; ?>
            <li class="mt-4">
                <a href="custom_report.php?type=health" class="text-sm text-blue-500 hover:text-blue-700">
                    <i class="fas fa-plus mr-1"></i> Create Custom Health Report
                </a>
            </li>
        </ul>
    </div>
    
    <!-- Sales Reports -->
    <div class="bg-white rounded-lg shadow p-6">
        <h2 class="text-lg font-semibold mb-4">Sales Reports</h2>
        <ul class="space-y-2">
            <?php if (isset($grouped_templates['sales'])): ?>
                <?php foreach ($grouped_templates['sales'] as $template): ?>
                    <li>
                        <a href="generate.php?template_id=<?php echo $template['id']; ?>" class="flex items-center p-2 hover:bg-blue-50 rounded">
                            <i class="fas fa-shopping-cart text-indigo-500 mr-2"></i>
                            <span><?php echo htmlspecialchars($template['template_name']); ?></span>
                        </a>
                    </li>
                <?php endforeach; ?>
            <?php else: ?>
                <li class="text-gray-500">No sales report templates available</li>
            <?php endif; ?>
            <li class="mt-4">
                <a href="custom_report.php?type=sales" class="text-sm text-blue-500 hover:text-blue-700">
                    <i class="fas fa-plus mr-1"></i> Create Custom Sales Report
                </a>
            </li>
        </ul>
    </div>
</div>

<?php require_once '../../includes/footer.php'; ?>

